// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjR55enDF1sUVdqPh3gnjvhLcjWqI-ehQ',
    appId: '1:266019884534:web:cb89eae5f686ff87760bd7',
    messagingSenderId: '266019884534',
    projectId: 'note-base-103d3',
    authDomain: 'note-base-103d3.firebaseapp.com',
    storageBucket: 'note-base-103d3.appspot.com',
    measurementId: 'G-H79YV598RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwADCfTYD2pQ9gq1LY1t0J-YX7qBwQo6w',
    appId: '1:266019884534:android:ef683bf8b1f9f57c760bd7',
    messagingSenderId: '266019884534',
    projectId: 'note-base-103d3',
    storageBucket: 'note-base-103d3.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjR55enDF1sUVdqPh3gnjvhLcjWqI-ehQ',
    appId: '1:266019884534:web:bc5d201c66279bd8760bd7',
    messagingSenderId: '266019884534',
    projectId: 'note-base-103d3',
    authDomain: 'note-base-103d3.firebaseapp.com',
    storageBucket: 'note-base-103d3.appspot.com',
    measurementId: 'G-YM2NB987GW',
  );
}
